[package]
name = "space"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.30.9"
hecs = "0.10.5"
miniquad = "0.4.8"
rand = "0.9.2"
rapier3d = { version = "0.26.1", features = [ "simd-stable", "parallel" ] }
